// IDIOMAS — castellano (idioma base del código) y català.
// t('texto en castellano') devuelve la traducción al idioma activo; si falta,
// devuelve el original. Así las misiones del Admin (DLC) siguen funcionando
// aunque no tengan traducción. Variables: t('Hola {n}', { n: 'Goku' }).
//
// El català sigue el doblatge mític de TV3 («Bola de Drac»): Follet Tortuga,
// Cor Petit, Xixi, Iamxa, Pual, núvol Kinton, mongetes màgiques...
// PERÒ es manté «Kamehameha» (mai «ona vital»).
import { reactive } from 'vue'

export const LANGS = { es: 'Castellano', ca: 'Català' }
export const i18n = reactive({ lang: 'es' })

export function t (s, vars) {
  if (s == null) return ''
  let out = i18n.lang === 'ca' ? (CA[s] ?? s) : s
  if (vars) out = out.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? m)
  return out
}
// traducción de un texto que puede venir de datos (Admin) con campos por idioma:
// 'texto' | { es: 'texto', ca: 'text' }
export function tx (v) {
  if (v && typeof v === 'object') return v[i18n.lang] ?? v.es ?? ''
  return t(v)
}

// Nombres de personajes en català (por id de sprite)
export const NAMES_CA = {
  roshi: 'Follet Tortuga',
  chichi: 'Xixi',
  chichi_nina: 'Xixi (nena)',
  piccolo: 'Cor Petit',
  yamcha: 'Iamxa',
  yamcha_z: 'Iamxa',
  puar: 'Pual',
  gyumao: 'Rei Bou',
  umigame: 'Tortuga Marina',
  shenron: 'Shenron',
  kaio: 'Kaito',
  goku_nino: 'Son Goku (nen)',
  bulma_joven: 'Bulma',
  dino: 'Dinosaure',
  a16: 'Androide 16',
  a17: 'Androide 17',
  a18: 'Androide 18',
  cell: 'Cèl·lula',
  buu: 'Buu',
  freezer: 'Freezer'
}

const CA = {
  // ------------------------------------------------------------ INTERFÍCIE
  'TOCA PARA EMPEZAR': 'TOCA PER COMENÇAR',
  'CARGANDO...': 'CARREGANT...',
  'Fan game sin ánimo de lucro · prototipo': 'Fan game sense ànim de lucre · prototip',
  'Las bolas de dragón': 'Les boles de drac',
  'Modo Historia': 'Mode Història',
  'Mundo abierto': 'Món obert',
  'Capítulo {n}': 'Capítol {n}',
  'Cap. {n}': 'Cap. {n}',
  'Lo vives como: {h}': 'Ho vius com a: {h}',
  'Eres {h}': 'Ets {h}',
  'Leer': 'Llegir',
  'Releer': 'Rellegir',
  'Continuar': 'Continuar',
  'Continuar ▶': 'Continuar ▶',
  'Toca los objetos de la viñeta · pistas clave: {a}/{b}': 'Toca els objectes de la vinyeta · pistes clau: {a}/{b}',
  '¡Casi! ¿Lo intentas otra vez?': 'Gairebé! Ho tornes a provar?',
  'Reintentar': 'Tornar-ho a provar',
  'Seguir leyendo': 'Continuar llegint',
  '¡Fin del capítulo {n}!': 'Fi del capítol {n}!',
  'Siguiente capítulo ▶': 'Capítol següent ▶',
  'Índice del libro': 'Índex del llibre',
  'Ajustes': 'Opcions',
  'Huir': 'Fugir',
  'Minijuego desconocido: {g}': 'Minijoc desconegut: {g}',
  '¡MISIÓN COMPLETADA!': 'MISSIÓ COMPLERTA!',
  '{title} · +{z} zenis': '{title} · +{z} zenis',
  'Equipo': 'Equip',
  'Nuevo personaje disponible: {c}': 'Nou personatge disponible: {c}',
  'Vuelves a tu forma normal': 'Tornes a la teva forma normal',
  'Esta misión empieza en {p}': 'Aquesta missió comença a {p}',
  '¡Conseguido: {i}!': 'Aconseguit: {i}!',
  'Esfera de 4 estrellas': 'Bola de 4 estrelles',
  'Radar del dragón': 'Radar del drac',
  'Semilla del ermitaño': 'Mongeta màgica',
  'Scouter de Raditz': 'Scouter d\'en Raditz',
  'Hace mucho tiempo, siete esferas mágicas fueron repartidas por el mundo...': 'Fa molt de temps, set boles màgiques es van escampar pel món...',
  'Quien las reúna podrá invocar al dragón Shenlong y pedirle un deseo.': 'Qui les reuneixi podrà invocar el drac Shenron i demanar-li un desig.',
  '¡Hola! Soy Goku. Gira el mundo con el dedo y toca la Montaña Paoz, ¡mi casa!': 'Hola! Sóc en Goku. Fes girar el món amb el dit i toca la Muntanya Paoz, casa meva!',
  // globo
  '🔒 Mundo bloqueado — llegará en un pack de misiones (DLC).': '🔒 Món bloquejat — arribarà en un paquet de missions (DLC).',
  '🔒 Completa antes: «{t}»': '🔒 Completa abans: «{t}»',
  'No hay misiones nuevas aquí... de momento.': 'Aquí no hi ha missions noves... de moment.',
  'Entrar ▶': 'Entrar ▶',
  '☁ Volar en la Nube Kinton': '☁ Volar amb el núvol Kinton',
  '🎲 Tirar dado': '🎲 Tirar el dau',
  'Acercar': 'Apropar',
  'Alejar': 'Allunyar',
  'Centrar en el personaje': 'Centrar en el personatge',
  'Arrastra · Pellizca para acercar · Toca un lugar': 'Arrossega · Pessiga per apropar · Toca un lloc',
  'Modo: {m}': 'Mode: {m}',
  '🎲 Dados': '🎲 Daus',
  '🕊 Libre': '🕊 Lliure',
  'Has llegado a {p}': 'Has arribat a {p}',
  'Evento': 'Esdeveniment',
  'Te cruzas con Yamcha en el desierto. Se pone rojo y huye. +10 zenis': 'Et creues amb l\'Iamxa al desert. Es posa vermell i fuig. +10 zenis',
  'Un pterodáctilo te adelanta. Le ganas. +10 zenis': 'Un pterodàctil t\'avança. El guanyes. +10 zenis',
  'Encuentras una cápsula perdida... ¡es una nevera llena! +10 zenis': 'Trobes una càpsula perduda... és una nevera plena! +10 zenis',
  'El Ejército Red Ribbon patrulla a lo lejos. Mejor seguir. +10 zenis': 'L\'exèrcit de la Cinta Vermella patrulla lluny. Millor continuar. +10 zenis',
  'Puar se transforma en nube para volar a tu lado un rato. +10 zenis': 'En Pual es transforma en núvol per volar al teu costat una estona. +10 zenis',
  // lugar
  '◀ Globo': '◀ Globus',
  'Misiones aquí': 'Missions aquí',
  'Empezar': 'Començar',
  '⭐ Misión en curso: {t}': '⭐ Missió en curs: {t}',
  'Continúa en': 'Continua a',
  '✅ ¡Lo has completado todo aquí!': '✅ Ho has completat tot aquí!',
  'Siguiente aventura: «{m}» en {l}. Vuelve al globo para viajar.': 'Propera aventura: «{m}» a {l}. Torna al globus per viatjar.',
  'Pronto llegarán nuevas misiones (DLC). ¡Habla con todos para descubrir secretos!': 'Aviat arribaran missions noves (DLC). Parla amb tothom per descobrir secrets!',
  '⚡ Transformarse': '⚡ Transformar-se',
  'Tirar': 'Tirar',
  '¡Has sacado un {n}!': 'Has tret un {n}!',
  'No puedo llegar hasta ahí': 'No hi puc arribar',
  'Tira el dado para moverte 🎲': 'Tira el dau per moure\'t 🎲',
  'Paso {a}/{b}': 'Pas {a}/{b}',
  'Misión': 'Missió',
  // ajustes
  '◀ Volver': '◀ Tornar',
  'Idioma': 'Idioma',
  'Modo de avance': 'Mode d\'avanç',
  '🕊 Avance libre': '🕊 Avanç lliure',
  'Toca donde quieras ir y el personaje camina (o vuela) hasta allí.': 'Toca on vulguis anar i el personatge hi camina (o hi vola).',
  '🎲 Avance con dados': '🎲 Avanç amb daus',
  'Tira el dado y avanza esas casillas, en el globo y dentro de cada lugar. Hay casillas-evento por el camino.': 'Tira el dau i avança aquestes caselles, al globus i dins de cada lloc. Hi ha caselles-esdeveniment pel camí.',
  'Gráficos y sonido': 'Gràfics i so',
  'Estilo gráfico': 'Estil gràfic',
  'Resolución': 'Resolució',
  'Máxima · nítido': 'Màxima · nítid',
  'Alta · retro sutil': 'Alta · retro subtil',
  'Media · retro suave': 'Mitjana · retro suau',
  'Baja · 8 bits clásico': 'Baixa · 8 bits clàssic',
  'Música': 'Música',
  'Diálogos (estilo cómic)': 'Diàlegs (estil còmic)',
  'Tipo de letra': 'Tipus de lletra',
  'Tamaño del texto': 'Mida del text',
  'Pequeño': 'Petita',
  'Normal': 'Normal',
  'Grande': 'Gran',
  'Enorme': 'Enorme',
  'Velocidad del texto': 'Velocitat del text',
  'Lenta': 'Lenta',
  'Rápida': 'Ràpida',
  'Instantánea': 'Instantània',
  '¡Así se verán los bocadillos!': 'Així es veuran les bafarades!',
  'Partida': 'Partida',
  'Guardado {w}.': 'Desat {w}.',
  'en la nube (Firebase)': 'al núvol (Firebase)',
  'en este dispositivo': 'en aquest dispositiu',
  'Borrar progreso': 'Esborrar el progrés',
  '¿Seguro? Se perderá todo el progreso.': 'Segur? Es perdrà tot el progrés.',
  'Personajes': 'Personatges',
  '🎨 Personajes (editar sprites)': '🎨 Personatges (editar sprites)',
  '🛠 Admin (misiones DLC)': '🛠 Admin (missions DLC)',
  // estilos gráficos
  'Bloques de construcción': 'Blocs de construcció',
  'Dibujo animado': 'Dibuix animat',
  'Pixel-art retro': 'Pixel-art retro',
  'Faltan {n} casillas': 'Falten {n} caselles',
  'Pasos: {n}': 'Passos: {n}',

  // ------------------------------------------------------------ MINIJOCS
  'Piedra': 'Pedra',
  'Papel': 'Paper',
  'Tijera': 'Tisores',
  '¡GANAS!': 'GUANYES!',
  '¡PIERDES!': 'PERDS!',
  '¡EMPATE!': 'EMPAT!',
  'Aprieta el puño con fuerza...': 'Estreny el puny amb força...',
  'Abre mucho la mano, como para atrapar algo...': 'Obre molt la mà, com per atrapar alguna cosa...',
  'Mueve dos dedos: chac, chac...': 'Mou dos dits: xac, xac...',
  '¡Elige!': 'Tria!',
  '¡Jan...': 'Jan...',
  '...Ken...': '...Ken...',
  '¡PON!': 'PON!',
  'Empiezas tú: consigue tres esferas en línea.': 'Comences tu: fes tres boles en ratlla.',
  '¡Tres en raya!': 'Tres en ratlla!',
  '¡{e} gana esta!': 'Aquesta la guanya {e}!',
  '¡Empate!': 'Empat!',
  'Nueva partida.': 'Nova partida.',
  '{e} piensa...': '{e} pensa...',
  'Tu turno.': 'Et toca.',
  'Ronda {a}/{b} · Aciertos {h}': 'Ronda {a}/{b} · Encerts {h}',
  '¿Qué palabra rima?': 'Quina paraula rima?',
  'Carga {a}/{b}': 'Càrrega {a}/{b}',
  'Observa el ki...': 'Observa l\'energia...',
  '¡Tu turno! Repite la secuencia': 'Et toca! Repeteix la seqüència',
  'Fuego': 'Foc',
  'Agua': 'Aigua',
  'Rayo': 'Llamp',
  'Viento': 'Vent',
  '¡Las gafas están aquí! No las pierdas de vista.': 'Les ulleres són aquí! No les perdis de vista.',
  'El agua ultrasagrada está aquí. ¡No la pierdas de vista!': 'L\'aigua sagrada és aquí. No la perdis de vista!',
  '{e} lo mezcla todo...': '{e} ho barreja tot...',
  '¿Bajo qué concha están las gafas?': 'Sota quina petxina hi ha les ulleres?',
  '¿Dónde está el agua?': 'On és l\'aigua?',
  '¡Bien visto!': 'Ben vist!',
  '¡Fallaste!': 'Has fallat!',
  'Pregunta {a}/{b} · Aciertos {h}': 'Pregunta {a}/{b} · Encerts {h}',
  '¡Tira cuando el pez muerda!': 'Estira quan el peix mossegui!',
  '¡TIRAR!': 'ESTIRA!',
  '¡Picó!': 'Ha picat!',
  '¡Se escapó!': 'S\'ha escapat!',
  'Sintoniza la frecuencia en la zona verde': 'Sintonitza la freqüència a la zona verda',
  '¡SINTONIZAR!': 'SINTONITZA!',
  '¡Señal captada!': 'Senyal captat!',
  'Solo ruido...': 'Només soroll...',
  'Intento {a}/{b}': 'Intent {a}/{b}',
  '¡Estira el bastón cuando pase el pterodáctilo!': 'Allarga el bastó quan passi el pterodàctil!',
  '¡CRECE, NYOIBO!': 'CREIX, NYOIBO!',
  '¡Le has dado!': 'L\'has tocat!',
  '¡Ha esquivado el bastón!': 'Ha esquivat el bastó!',
  '¡Grita tu deseo justo cuando Pilaf tome aire!': 'Crida el teu desig just quan en Pilaf agafi aire!',
  '¡QUIERO...!': 'VULL...!',
  '¡Te ha oído Shenron!': 'T\'ha sentit en Shenron!',
  '¡Pilaf te ha tapado la boca!': 'En Pilaf t\'ha tapat la boca!',
  'Suelta la onda cuando la energía esté a tope': 'Llança l\'ona quan l\'energia sigui al màxim',
  '¡KAMEHAMEHA!': 'KAMEHAMEHA!',
  '¡Onda perfecta!': 'Ona perfecta!',
  '¡Se ha deshecho!': 'S\'ha desfet!',
  'Aciertos': 'Encerts',
  'Parejas {a}/{b} · Intentos {n}': 'Parelles {a}/{b} · Intents {n}',
  'Casa': 'Casa', 'Moto': 'Moto', 'Avión': 'Avió', 'Lancha': 'Llanxa', 'Nevera': 'Nevera', 'Coche': 'Cotxe', 'Robot': 'Robot', 'Nave': 'Nau',
  'Jan-Ken · Piedra, papel o tijera': 'Jan-Ken · Pedra, paper o tisores',
  'Lee la pista del rival y gana al mejor de N.': 'Llegeix la pista del rival i guanya al millor de N.',
  'Tres en raya': 'Tres en ratlla',
  'Consigue tres esferas del dragón en línea.': 'Fes tres boles de drac en ratlla.',
  'Duelo de rimas': 'Duel de rimes',
  'Elige la palabra que rima antes de que se agote el ki.': 'Tria la paraula que rima abans que s\'acabi l\'energia.',
  'Secuencia de ki': 'Seqüència d\'energia',
  'Repite la secuencia de energía. Cada vez es más larga.': 'Repeteix la seqüència d\'energia. Cada cop és més llarga.',
  'Sigue el objeto': 'Segueix l\'objecte',
  'Vigila dónde queda el premio mientras lo mezclan.': 'Vigila on queda el premi mentre ho barregen.',
  'Examen sorpresa': 'Examen sorpresa',
  'Responde bien a la mayoría de preguntas antes de que acabe el tiempo.': 'Respon bé la majoria de preguntes abans que s\'acabi el temps.',
  'Reflejos': 'Reflexos',
  'Pulsa justo cuando la aguja esté en la zona verde.': 'Prem just quan l\'agulla sigui a la zona verda.',
  'Memoria de cápsulas': 'Memòria de càpsules',
  'Encuentra todas las parejas antes de quedarte sin intentos.': 'Troba totes les parelles abans de quedar-te sense intents.',
  'Carrera': 'Cursa',
  '¡PAM!': 'PAM!', '¡ZAS!': 'ZAS!', '¡BIEN!': 'BÉ!', '¡BOOM!': 'BUM!', '¡AUCH!': 'AI!',

  // ------------------------------------------------------------ MONS I LLOCS
  'La Tierra': 'La Terra',
  'Saga de las Esferas · Saga Saiyan': 'Saga de les Boles · Saga Saiyan',
  'Línea principal': 'Línia principal',
  'Montaña Paoz': 'Muntanya Paoz',
  'Bosques, ríos y la casita donde el abuelo Gohan crió a Goku.': 'Boscos, rius i la caseta on l\'avi Gohan va criar en Goku.',
  'Kame House': 'Kame House',
  'Una isla diminuta en mitad del mar. El Maestro Roshi entrena (y lee revistas) aquí.': 'Una illa minúscula enmig del mar. El Follet Tortuga hi entrena (i hi llegeix revistes).',
  'Capsule Corp': 'Corporació Càpsula',
  'La cúpula de la familia Brief en la Capital del Oeste. Todo cabe en una cápsula.': 'La cúpula de la família Brief a la Capital de l\'Oest. Tot hi cap, en una càpsula.',
  'Torre Karin': 'Torre d\'en Karin',
  'Una torre tan alta que atraviesa las nubes. Arriba espera un gato muy sabio.': 'Una torre tan alta que travessa els núvols. A dalt hi espera un gat molt savi.',
  'Planeta de Kaio': 'Planeta d\'en Kaito',
  'Saga Saiyan': 'Saga Saiyan',
  'Línea principal (Más Allá)': 'Línia principal (el Més Enllà)',
  'Casa de Kaio': 'Casa d\'en Kaito',
  'Gravedad x10, un mono llamado Bubbles y chistes malos.': 'Gravetat x10, un mico que es diu Bubbles i acudits dolents.',
  'Namek': 'Namek',
  'Saga Freezer': 'Saga Freezer',
  'Aldea de Guru': 'Poblat d\'en Guru',
  'Casas-cúpula y siete esferas gigantes.': 'Cases-cúpula i set boles gegants.',
  'Nave de Freezer': 'Nau d\'en Freezer',
  'Aquí nadie te recibe con té.': 'Aquí ningú no et rep amb te.',
  'Tierra del Futuro': 'Terra del Futur',
  'Saga Androides': 'Saga dels Androides',
  'Línea paralela de Trunks': 'Línia paral·lela d\'en Trunks',
  'Ruinas de la Capital': 'Ruïnes de la Capital',
  'Un mundo arrasado por los androides 17 y 18.': 'Un món arrasat pels androides 17 i 18.',
  'Máquina del Tiempo': 'Màquina del Temps',
  'Bulma del futuro trabaja sin descanso.': 'La Bulma del futur treballa sense descans.',
  'Casa del abuelo Gohan': 'Casa de l\'avi Gohan',
  'Mi casa. Huele a arroz y a leña. ¡Qué hambre!': 'Casa meva. Fa olor d\'arròs i de llenya. Quina gana!',
  'Altar del abuelo': 'Altar de l\'avi',
  'Abuelito, hoy también voy a entrenar mucho.': 'Avi, avui també entrenaré molt.',
  '¡Goku! Si ves a Gohan jugando en vez de estudiar, me lo traes. ¡Y lávate las manos antes de cenar!': 'Goku! Si veus en Gohan jugant en comptes d\'estudiar, me\'l portes. I renta\'t les mans abans de sopar!',
  'Cartel': 'Cartell',
  '«MONTAÑA PAOZ. Cuidado con los dinosaurios. Y con los tigres. Y con Goku.»': '«MUNTANYA PAOZ. Compte amb els dinosaures. I amb els tigres. I amb en Goku.»',
  'Una casa rosa con el rótulo KAME HOUSE. ¡Qué pequeña es la isla!': 'Una casa rosa amb el rètol KAME HOUSE. Que petita que és l\'illa!',
  'Maestro Roshi': 'Follet Tortuga',
  'Jo, jo, jo. ¿Has traído alguna revista... educativa?': 'Jo, jo, jo. Que m\'has portat alguna revista... educativa?',
  '¡Eh! Yo llegué primero. El maestro es mío... bueno, compartimos.': 'Ei! Jo hi vaig arribar primer. El mestre és meu... bé, el compartim.',
  'Llevo mil años viviendo con el Maestro Roshi. He visto cosas... que es mejor no contar.': 'Fa mil anys que visc amb el Follet Tortuga. He vist coses... que val més no explicar.',
  'Palmera': 'Palmera',
  'Una palmera. Tiene cocos. ¿Se comerán?': 'Una palmera. Té cocos. Es deuen poder menjar?',
  'Capsule Corporation': 'Corporació Càpsula',
  'Una casa redonda como un bollo gigante.': 'Una casa rodona com un brioix gegant.',
  '¡No toques nada! Todo aquí es un prototipo… o explota.': 'No toquis res! Aquí tot és un prototip… o explota.',
  'Yo solo pasaba por aquí. No he cogido nada. ¿Por qué me miras así?': 'Jo només passava per aquí. No he agafat res. Per què em mires així?',
  'Caja de cápsulas': 'Capsa de càpsules',
  'Cápsulas numeradas: casa, moto, avión... ¡y nevera!': 'Càpsules numerades: casa, moto, avió... i nevera!',
  'Has subido toda la torre sin volar. Interesante, muchacho.': 'Has pujat tota la torre sense volar. Interessant, noi.',
  'Agua Ultrasagrada': 'Aigua Sagrada',
  'Una jarra que brilla. Seguro que no está tan rica como parece.': 'Una gerra que brilla. Segur que no és tan bona com sembla.',
  'Columna': 'Columna',
  'Desde aquí se ve toda la Tierra. ¡Y el Palacio de Kamisama arriba!': 'Des d\'aquí es veu tota la Terra. I a dalt, el Palau d\'en Kami-sama!',

  // ------------------------------------------------------------ NOMS
  'Narrador': 'Narrador',
  'Goku': 'Goku',
  'Gohan': 'Gohan',
  'Chichí': 'Xixi',
  'Krilin': 'Krilin',
  'Roshi': 'Follet Tortuga',
  'Umigame': 'Tortuga Marina',
  'Raditz': 'Raditz',
  'Piccolo': 'Cor Petit',
  'Bulma': 'Bulma',
  'Oolong': 'Oolong',
  'Karin': 'Karin',
  'Scouter': 'Scouter',
  'Dinosaurio': 'Dinosaure',
  'Yamcha': 'Iamxa',
  'Puar': 'Pual',

  // ------------------------------------------------------------ MISSIONS · PAOZ
  'Recuerdo: la esfera de cuatro estrellas': 'Record: la bola de quatre estrelles',
  'Años atrás, un Goku muy pequeño pierde el tesoro de su abuelo... por culpa de un dinosaurio con hambre.': 'Anys enrere, un Goku molt petit perd el tresor del seu avi... per culpa d\'un dinosaure amb gana.',
  'Hace muchos años, en la Montaña Paoz, vivía un niño con cola que comía más que diez leñadores.': 'Fa molts anys, a la Muntanya Paoz, hi vivia un nen amb cua que menjava més que deu llenyataires.',
  '¡Buenos días, abuelito! ...¿Eh? ¿Dónde está tu esfera?': 'Bon dia, avi! ...Eh? On és la teva bola?',
  'Huellas gigantes': 'Petjades gegants',
  'Dinosaurio glotón': 'Dinosaure golafre',
  'Mira el altar del abuelo (junto a la casa).': 'Mira l\'altar de l\'avi (al costat de la casa).',
  'El cojín está vacío... ¡La esfera de cuatro estrellas no está!': 'El coixí és buit... La bola de quatre estrelles no hi és!',
  'Hay barro en el suelo. Algo MUY grande ha pasado por aquí.': 'Hi ha fang a terra. Alguna cosa MOLT grossa ha passat per aquí.',
  'Sigue el rastro hacia el río.': 'Segueix el rastre cap al riu.',
  'Huellas de tres dedos... y huelen a pescado. ¡Un dinosaurio!': 'Petjades de tres dits... i fan pudor de peix. Un dinosaure!',
  'Van hacia las rocas del sureste.': 'Van cap a les roques del sud-est.',
  'Enfréntate al dinosaurio.': 'Enfronta\'t al dinosaure.',
  '¡GROAAAR! (Se relame. Tiene algo brillante entre los dientes.)': 'GROAAAR! (Es llepa. Té una cosa brillant entre les dents.)',
  '¡Devuélvemela! Te reto al Jan-Ken: ¡piedra, papel o tijera!': 'Torna-me-la! Et repto al Jan-Ken: pedra, paper o tisores!',
  '¡GROA...! ¡Achís! (La esfera sale disparada y rueda por la hierba.)': 'GROA...! Atxim! (La bola surt disparada i rodola per l\'herba.)',
  '¡GROAR! (Se ríe con la boca llena. Quiere la revancha.)': 'GROAR! (Riu amb la boca plena. Vol la revenja.)',
  'Recoge la esfera.': 'Recull la bola.',
  '¡La tengo! Brilla como un sol pequeñito... Abuelito, ya estás en casa.': 'La tinc! Brilla com un sol petitó... Avi, ja ets a casa.',
  'Años después, esa misma esfera brillará en el sombrero del hijo de Goku...': 'Anys després, aquesta mateixa bola brillarà al barret del fill d\'en Goku...',
  '¡Gohan tiene que estudiar!': 'En Gohan ha d\'estudiar!',
  'Chichí quiere un hijo investigador. Gohan quiere perseguir mariposas. Goku... quiere comer.': 'La Xixi vol un fill investigador. En Gohan vol perseguir papallones. En Goku... vol menjar.',
  'Montaña Paoz, cinco años después. Goku ya es padre... y Chichí tiene un plan: ¡su hijo será un gran investigador!': 'Muntanya Paoz, cinc anys després. En Goku ja és pare... i la Xixi té un pla: el seu fill serà un gran investigador!',
  'Huellas pequeñitas': 'Petjades petitones',
  'Habla con Chichí.': 'Parla amb la Xixi.',
  '¡Goku! Gohan se ha escapado OTRA VEZ en mitad de la lección de álgebra.': 'Goku! En Gohan s\'ha escapat UNA ALTRA VEGADA enmig de la lliçó d\'àlgebra.',
  'Tráelo de vuelta. ¡Y ni se te ocurra enseñarle a pelear!': 'Porta-me\'l. I ni se t\'acudeixi ensenyar-li a lluitar!',
  'Jejeje... vale, vale.': 'Jejeje... d\'acord, d\'acord.',
  'Busca pistas de Gohan.': 'Busca pistes d\'en Gohan.',
  'Huellas pequeñitas... y un libro abandonado: «Matemáticas para genios de cuatro años».': 'Petjades petitones... i un llibre abandonat: «Matemàtiques per a genis de quatre anys».',
  'Van hacia el río. ¡Gohan, sal de donde estés!': 'Van cap al riu. Gohan, surt d\'on siguis!',
  'Encuentra a Gohan junto al río.': 'Troba en Gohan al costat del riu.',
  '¡Papá! No me escapé... ¡estaba estudiando a los peces! Eso también es ciencia.': 'Papa! No m\'he escapat... estudiava els peixos! Això també és ciència.',
  'Jajaja. Anda, volvamos, que tu madre da más miedo que un dinosaurio.': 'Ha, ha, ha. Au, tornem, que la teva mare fa més por que un dinosaure.',
  'Supera el examen de Chichí.': 'Supera l\'examen de la Xixi.',
  'Para comprobar que ha estudiado... ¡un examen! Y tú también, Goku. Ayúdale.': 'Per comprovar que ha estudiat... un examen! I tu també, Goku. Ajuda\'l.',
  '¿Un examen? Prefiero pelear con Piccolo...': 'Un examen? M\'estimo més lluitar amb en Cor Petit...',
  '¡Sobresaliente! Bueno... podéis ir a visitar a vuestros amigos a Kame House.': 'Excel·lent! Bé... podeu anar a visitar els vostres amics a Kame House.',
  '¡Bieeen! ¿Me llevas en la Nube Kinton, papá?': 'Visca! Em portes amb el núvol Kinton, papa?',
  '¡Suspenso! Otra vez a la mesa. ¡Y nada de postre!': 'Suspès! Una altra vegada a taula. I res de postres!',
  'La cena de los Saiyans': 'El sopar dels Saiyans',
  'La despensa está vacía y en casa hay dos estómagos Saiyan. Toca pescar... a lo grande.': 'El rebost és buit i a casa hi ha dos estómacs Saiyan. Toca pescar... a lo gran.',
  '¡No queda NADA en la despensa! Y vosotros dos coméis por veinte.': 'No queda RES al rebost! I vosaltres dos mengeu per vint.',
  'Poza del río': 'Gorg del riu',
  'Traedme el pez más grande del río. ¡Y sin destrozar la cocina como la última vez!': 'Porteu-me el peix més gros del riu. I sense destrossar la cuina com l\'última vegada!',
  '¡Hecho! Gohan, hoy aprendes el método Son: ¡pescar con la cola!': 'Fet! Gohan, avui aprens el mètode Son: pescar amb la cua!',
  'Pesca el pez gigante en la poza.': 'Pesca el peix gegant al gorg.',
  '¡Papá, algo enorme está mordiendo mi cola!': 'Papa, una cosa enorme em mossega la cua!',
  '¡Espera a que pique y tira justo en el momento! ¡Ahora no... ahora no... AHORA!': 'Espera que piqui i estira just en el moment! Ara no... ara no... ARA!',
  '¡Un pez tan grande como la casa! Esa noche nadie pasa hambre en la Montaña Paoz.': 'Un peix tan gros com la casa! Aquella nit ningú no passa gana a la Muntanya Paoz.',
  'El pez se escapa salpicando a Goku de arriba abajo. Gohan no puede parar de reír.': 'El peix s\'escapa i esquitxa en Goku de dalt a baix. En Gohan no pot parar de riure.',
  'Lleva la cena a Chichí.': 'Porta el sopar a la Xixi.',
  '¡Así me gusta! Aunque... ¿cómo pensáis meter esto en la cazuela?': 'Així m\'agrada! Però... com penseu ficar això a la cassola?',
  '¡Por partes! Jejeje. ¿Hay postre?': 'A trossos! Jejeje. Hi ha postres?',

  // ------------------------------------------------------------ MISSIONS · KAME HOUSE
  'La reunión en Kame House': 'La trobada a Kame House',
  'Los viejos amigos se reúnen... y descubren que Goku tiene un hijo. Roshi lo celebra a su manera.': 'Els vells amics es retroben... i descobreixen que en Goku té un fill. El Follet Tortuga ho celebra a la seva manera.',
  'Cinco años después del último Torneo de Artes Marciales, los amigos se reúnen en la isla del Maestro Roshi.': 'Cinc anys després de l\'últim Torneig d\'Arts Marcials, els amics es retroben a l\'illa del Follet Tortuga.',
  'Saluda a Krilin.': 'Saluda en Krilin.',
  '¡Goku! ¡Cuánto tiempo! ¿Y ese niño que se esconde detrás de ti?': 'Goku! Quant de temps! I aquest nen que s\'amaga darrere teu?',
  '¡Es mi hijo! Se llama Gohan, como mi abuelo.': 'És el meu fill! Es diu Gohan, com el meu avi.',
  '¿¡TU HIJO!? ¡Si tú no sabías ni lo que era casarse!': 'EL TEU FILL!? Si tu no sabies ni què era casar-se!',
  'Habla con el Maestro Roshi.': 'Parla amb el Follet Tortuga.',
  'Jo, jo, jo... Y lleva la esfera de cuatro estrellas en el sombrero. ¡Qué recuerdos!': 'Jo, jo, jo... I porta la bola de quatre estrelles al barret. Quins records!',
  'Celebremos el reencuentro como en mis tiempos: ¡con un duelo de rimas!': 'Celebrem el retrobament com en els meus temps: amb un duel de rimes!',
  'Duelo de rimas con Roshi.': 'Duel de rimes amb el Follet Tortuga.',
  'Yo digo una palabra y tú eliges la que rima. ¡El que pierda friega los platos!': 'Jo dic una paraula i tu tries la que rima. Qui perdi renta els plats!',
  '¡Jo, jo! Tienes oído de campeón.': 'Jo, jo! Tens oïda de campió.',
  'Pues me toca fregar a mí... como siempre.': 'Doncs em toca rentar a mi... com sempre.',
  '¡A fregar, Goku! Jo, jo, jo.': 'A rentar plats, Goku! Jo, jo, jo.',
  '¿Dónde están mis gafas?': 'On són les meves ulleres?',
  'El Maestro Roshi no ve nada sin sus gafas de sol. Umigame las escondió... y no recuerda dónde.': 'El Follet Tortuga no hi veu gens sense les ulleres de sol. La Tortuga Marina les va amagar... i no recorda on.',
  '¡Sin mis gafas de sol no distingo a Krilin de una bola de billar!': 'Sense les ulleres de sol no distingeixo en Krilin d\'una bola de billar!',
  '¡Oiga!': 'Escolti!',
  'Habla con Roshi.': 'Parla amb el Follet Tortuga.',
  'Umigame siempre lo guarda todo. ¡Pregúntale a ella!': 'La Tortuga Marina ho guarda tot. Pregunta-li a ella!',
  'Pregunta a Umigame (la tortuga).': 'Pregunta a la Tortuga Marina.',
  'Las escondí bajo una concha para que nadie las pisara... pero no recuerdo cuál.': 'Les vaig amagar sota una petxina perquè ningú no les trepitgés... però no recordo quina.',
  'Las moveré despacio... bueno, despacio para ser una tortuga.': 'Les mouré a poc a poc... bé, a poc a poc per ser una tortuga.',
  'Sigue la concha con las gafas.': 'Segueix la petxina amb les ulleres.',
  '¡Atento! Concha, concha, concha...': 'Atent! Petxina, petxina, petxina...',
  '¡Mis gafas! Ahora lo veo todo clarísimo... ¡Anda, si se ha hecho de noche! Jo, jo.': 'Les meves ulleres! Ara ho veig tot claríssim... Vaja, si s\'ha fet de nit! Jo, jo.',
  'Uy, esa concha estaba vacía. Solo había un cangrejo muy ofendido.': 'Ui, aquesta petxina era buida. Només hi havia un cranc molt ofès.',
  'El hermano del espacio': 'El germà de l\'espai',
  'Un guerrero con armadura aterriza en la isla. Dice ser el hermano de Goku... y viene a por Gohan.': 'Un guerrer amb armadura aterra a l\'illa. Diu que és el germà d\'en Goku... i ve a buscar en Gohan.',
  'De repente, algo cae del cielo junto a la isla. De la nave sale un guerrero con armadura y una melena interminable...': 'De sobte, una cosa cau del cel al costat de l\'illa. De la nau en surt un guerrer amb armadura i una cabellera interminable...',
  'Enfréntate al desconocido.': 'Enfronta\'t al desconegut.',
  'Así que tú eres Kakarotto. Has crecido... pero te has vuelto blando.': 'Així que tu ets en Kakarot. Has crescut... però t\'has tornat tou.',
  'Soy Raditz, tu hermano mayor. Eres un Saiyan, enviado de bebé a conquistar este planeta.': 'Sóc en Raditz, el teu germà gran. Ets un Saiyan, enviat de nadó a conquerir aquest planeta.',
  '¿Mi... hermano? ¡Yo me llamo Son Goku y la Tierra es mi hogar!': 'El meu... germà? Jo em dic Son Goku i la Terra és casa meva!',
  'Protege a Gohan de Raditz.': 'Protegeix en Gohan d\'en Raditz.',
  'Si no te unes a mí, me llevaré a tu hijo.': 'Si no t\'uneixes a mi, m\'enduré el teu fill.',
  '¡No toques a Gohan! ¡Te reto al Jan-Ken, piedra, papel o tijera!': 'No toquis en Gohan! Et repto al Jan-Ken, pedra, paper o tisores!',
  '¡Grr! Tienes reflejos... pero mi nivel de pelea sigue siendo muy superior.': 'Grr! Tens reflexos... però el meu nivell de lluita continua sent molt superior.',
  'Patético. Mi scouter marca que tu nivel de pelea es solo de 334...': 'Patètic. El meu scouter diu que el teu nivell de lluita és només de 334...',
  'Detén a Raditz.': 'Atura en Raditz.',
  '¡Me llevo al niño! Si quieres recuperarlo, elimina a cien terrícolas antes de mañana.': 'M\'emporto el nen! Si el vols recuperar, elimina cent terrícoles abans de demà.',
  '¡Papááá!': 'Papaaa!',
  'Raditz despega con Gohan bajo el brazo. Entonces, una silueta con turbante aterriza en la arena...': 'En Raditz s\'enlaira amb en Gohan sota el braç. Aleshores, una silueta amb turbant aterra a la sorra...',
  'Habla con Piccolo.': 'Parla amb en Cor Petit.',
  'Ese Saiyan es un estorbo para mis planes de conquistar la Tierra.': 'Aquest Saiyan és un destorb per als meus plans de conquerir la Terra.',
  'Por esta vez lucharemos juntos, Goku. Tengo una técnica nueva: el Makankosappo.': 'Per aquesta vegada lluitarem junts, Goku. Tinc una tècnica nova: el Makankosappo.',
  '¿Piccolo... ayudándome a mí? ¡Esto sí que no me lo esperaba!': 'En Cor Petit... ajudant-me a mi? Això sí que no m\'ho esperava!',
  'Carga el Makankosappo con Piccolo.': 'Carrega el Makankosappo amb en Cor Petit.',
  'Necesito tiempo para concentrar mi ki. ¡Repite mi secuencia y no falles!': 'Necessito temps per concentrar la meva energia. Repeteix la meva seqüència i no fallis!',
  '¡El Makankosappo atraviesa a Raditz! Goku lo sujeta hasta el final... y se sacrifica para salvar a Gohan.': 'El Makankosappo travessa en Raditz! En Goku el subjecta fins al final... i se sacrifica per salvar en Gohan.',
  'Hmph. Las Esferas del Dragón te devolverán la vida. Mientras tanto, yo entrenaré al niño.': 'Hmf. Les boles de drac et tornaran la vida. Mentrestant, jo entrenaré el nen.',
  'En el Más Allá, un camino de un millón de kilómetros espera a Goku... (Continuará en el Planeta de Kaio)': 'Al Més Enllà, un camí d\'un milió de quilòmetres espera en Goku... (Continuarà al Planeta d\'en Kaito)',
  '¡Demasiado lento! Concéntrate o Raditz escapará.': 'Massa lent! Concentra\'t o en Raditz s\'escaparà.',

  // ------------------------------------------------------------ MISSIONS · CAPSULE CORP
  'El radar del dragón': 'El radar del drac',
  'Bulma necesita calibrar su radar... y alguien con cola de cerdo se ha llevado la pieza clave.': 'La Bulma ha de calibrar el radar... i algú amb cua de porc s\'ha endut la peça clau.',
  'Capital del Oeste. Coches voladores, robots y un laboratorio que huele a café recién hecho.': 'Capital de l\'Oest. Cotxes voladors, robots i un laboratori que fa olor de cafè acabat de fer.',
  'Habla con Bulma.': 'Parla amb la Bulma.',
  '¡Goku! Justo a tiempo. ¡Mi radar del dragón se ha vuelto loco!': 'Goku! Just a temps. El meu radar del drac s\'ha tornat boig!',
  'Repite la secuencia de ki exactamente como la marque la pantalla. Sin fallar.': 'Repeteix la seqüència d\'energia exactament com la marqui la pantalla. Sense fallar.',
  'Calibra el radar con Bulma.': 'Calibra el radar amb la Bulma.',
  'Rojo, azul, amarillo, verde... ¡Memoriza!': 'Vermell, blau, groc, verd... Memoritza!',
  '¡Perfecto! Solo falta el chip de antena... ¡OOLONG! ¡Devuélvelo ahora mismo!': 'Perfecte! Només falta el xip de l\'antena... OOLONG! Torna\'l ara mateix!',
  '¡Casi lo quemas! Venga, otra vez.': 'Gairebé el cremes! Au, una altra vegada.',
  'Recupera el chip de Oolong.': 'Recupera el xip d\'en Oolong.',
  '¿El chip? Te lo doy si me ganas al tres en raya. ¡Yo soy la X y tú la esfera!': 'El xip? Te\'l dono si em guanyes al tres en ratlla. Jo sóc la X i tu la bola!',
  'Bah... toma tu chip. Pero la nevera sigue siendo mía.': 'Bah... té el teu xip. Però la nevera continua sent meva.',
  '¡Ja! Los cerdos también somos listos.': 'Ha! Els porcs també som espavilats.',
  'El lío de las cápsulas': 'L\'embolic de les càpsules',
  'La madre de Bulma ha vaciado la caja de cápsulas para hacer sitio a sus galletas. ¡Hay que emparejarlas!': 'La mare de la Bulma ha buidat la capsa de càpsules per fer lloc a les galetes. Cal aparellar-les!',
  '¡MAMÁ! ¿Has sacado todas las cápsulas de su caja para guardar galletas?': 'MAMA! Has tret totes les càpsules de la capsa per guardar-hi galetes?',
  'Cada cápsula tiene su pareja de repuesto. Si las emparejo mal... ¡podría salir una casa dentro del laboratorio!': 'Cada càpsula té la seva parella de recanvi. Si les aparello malament... podria sortir una casa dins del laboratori!',
  'Yo tengo buena memoria para la comida. ¡Seguro que para esto también!': 'Jo tinc bona memòria per al menjar. Segur que per a això també!',
  'Empareja las cápsulas.': 'Aparella les càpsules.',
  'Destápalas de dos en dos. ¡Y cuidado con la número 7, que es un avión!': 'Destapa-les de dues en dues. I compte amb la número 7, que és un avió!',
  '¡Todas en su sitio! Casa, moto, avión, submarino... ¿y esta nevera?': 'Totes al seu lloc! Casa, moto, avió, submarí... i aquesta nevera?',
  '¡Nooo! Acaba de aparecer una moto en el jardín. Otra vez.': 'Nooo! Acaba d\'aparèixer una moto al jardí. Una altra vegada.',
  'Devuelve la nevera a Oolong.': 'Torna la nevera a l\'Oolong.',
  '¡Eh, esa nevera es mía! Vale, vale... toma un bocadillo como agradecimiento.': 'Ei, aquesta nevera és meva! Bé, bé... té un entrepà per agrair-t\'ho.',
  '¡Gracias, Oolong! ¿Solo uno?': 'Gràcies, Oolong! Només un?',
  'El scouter de Raditz': 'El scouter d\'en Raditz',
  'Bulma estudia el aparato que llevaba Raditz en el ojo. Lo que descubre no es nada bueno...': 'La Bulma estudia l\'aparell que en Raditz duia a l\'ull. El que descobreix no és gens bo...',
  'Tras la batalla contra Raditz, Krilin trae a la Capsule Corp el extraño aparato que el Saiyan llevaba en el ojo.': 'Després de la batalla contra en Raditz, en Krilin porta a la Corporació Càpsula l\'estrany aparell que el Saiyan duia a l\'ull.',
  'Esto es un scouter: mide el nivel de pelea... y ¡también es un comunicador!': 'Això és un scouter: mesura el nivell de lluita... i també és un comunicador!',
  'Sintoniza la frecuencia justo cuando la aguja pase por la zona verde.': 'Sintonitza la freqüència just quan l\'agulla passi per la zona verda.',
  'Sintoniza el scouter.': 'Sintonitza el scouter.',
  '¡Con cuidado! Si te pasas, se quema.': 'Amb compte! Si et passes, es crema.',
  '«...Raditz ha caído. Iremos a la Tierra a por las Esferas del Dragón. Llegaremos en un año. Vegeta, fuera.»': '«...En Raditz ha caigut. Anirem a la Terra a buscar les boles de drac. Hi arribarem d\'aquí a un any. Vegeta, fora.»',
  '¡Dos Saiyans más, todavía más fuertes que Raditz! Tenemos un año para prepararnos.': 'Dos Saiyans més, encara més forts que en Raditz! Tenim un any per preparar-nos.',
  'La Tierra se prepara para su mayor batalla... (Fin del primer mundo)': 'La Terra es prepara per a la seva batalla més gran... (Fi del primer món)',
  'Solo se oye ruido... ¡Inténtalo otra vez!': 'Només se sent soroll... Torna-ho a provar!',

  // ------------------------------------------------------------ MISSIONS · TORRE KARIN
  'El agua ultrasagrada': 'L\'aigua sagrada',
  'Karin guarda una jarra que te hará más fuerte... si consigues seguirle el ritmo.': 'En Karin guarda una gerra que et farà més fort... si aconsegueixes seguir-li el ritme.',
  'Tras escalar sin descanso, Goku llega a la cima de la Torre Karin, por encima de las nubes.': 'Després d\'escalar sense descans, en Goku arriba al cim de la Torre d\'en Karin, per sobre dels núvols.',
  'Habla con Karin.': 'Parla amb en Karin.',
  '¿Quieres el agua ultrasagrada? Esconderé la jarra entre tres. Sigue el movimiento.': 'Vols l\'aigua sagrada? Amagaré la gerra entre tres. Segueix el moviment.',
  'Sigue la jarra.': 'Segueix la gerra.',
  'No parpadees. Ni siquiera tu cola puede seguirme.': 'No parpellegis. Ni tan sols la teva cua em pot seguir.',
  'Bien visto. Como premio... una semilla del ermitaño. Está allí, junto al borde.': 'Ben vist. Com a premi... una mongeta màgica. És allà, a la vora.',
  'Demasiado lento. El Maestro Roshi tardó tres años. ¡Otra vez!': 'Massa lent. El Follet Tortuga hi va trigar tres anys. Una altra vegada!',
  'Recoge la semilla.': 'Recull la mongeta.',
  'Una judía pequeñita... ¡y me quita el hambre de golpe! Bueno, casi.': 'Una mongeta petitona... i em treu la gana de cop! Bé, gairebé.',
  'Las adivinanzas de Karin': 'Les endevinalles d\'en Karin',
  'Yajirobe se ha comido las semillas otra vez. Karin solo te dará la última si piensas tan rápido como luchas.': 'En Yajirobai s\'ha menjat les mongetes una altra vegada. En Karin només et donarà l\'última si penses tan ràpid com lluites.',
  'Yajirobe se ha vuelto a comer las semillas del ermitaño. ¡Ese glotón no tiene remedio!': 'En Yajirobai s\'ha tornat a menjar les mongetes màgiques. Aquest golafre no té remei!',
  'Me queda una sola. Te la daré si resuelves mis adivinanzas.': 'Me\'n queda només una. Te la donaré si resols les meves endevinalles.',
  '¿Adivinanzas? ¿No podemos echar una carrerita?': 'Endevinalles? No podem fer una cursa?',
  'Resuelve las adivinanzas de Karin.': 'Resol les endevinalles d\'en Karin.',
  'La mente también se entrena, muchacho.': 'La ment també s\'entrena, noi.',
  'Muy bien. Toma la última semilla... y escóndela de Yajirobe.': 'Molt bé. Té l\'última mongeta... i amaga-la d\'en Yajirobai.',
  'Hmm. Medita un poco más y vuelve a intentarlo.': 'Hmm. Medita una mica més i torna-ho a provar.'
}

// ------------------------------------------------------------ CONTINGUT DELS MINIJOCS EN CATALÀ
// Les rimes no es poden traduir paraula per paraula: tenen la seva pròpia llista
export const RHYMES_CA = [
  ['drac', 'llac'], ['bola', 'cassola'], ['tortuga', 'arruga'], ['estel', 'cel'],
  ['poder', 'carrer'], ['cua', 'grua'], ['muntanya', 'castanya'], ['guerrer', 'ferrer'],
  ['mongeta', 'bicicleta'], ['torre', 'corre'], ['revista', 'pista'], ['estrella', 'paella'],
  ['batalla', 'rialla'], ['escut', 'salut'], ['illa', 'vainilla'], ['entrenar', 'esmorzar'],
  ['zenis', 'tennis'], ['mar', 'volar'], ['nau', 'clau'], ['Kinton', 'bombó']
]

export const QUIZ_CA = {
  examen: [
    ['Quantes boles de drac s\'han de reunir per invocar en Shenron?', '7', '5', '9', '12'],
    ['Si en Goku menja 3 bols d\'arròs per àpat i fa 4 àpats... quants bols menja?', '12', '7', '9', '16'],
    ['Com es diu el núvol groc d\'en Goku?', 'Kinton', 'Kamehame', 'Kaito', 'Karin'],
    ['A quina capital hi ha la Corporació Càpsula?', 'Capital de l\'Oest', 'Capital del Nord', 'Ciutat Satan', 'Poble Pingüí'],
    ['Quantes estrelles té la bola del barret d\'en Gohan?', '4', '1', '7', '3'],
    ['Si una mongeta màgica cura 1 guerrer, quantes en calen per a 5?', '5', '1', '10', '3'],
    ['Quin animal és la Tortuga Marina?', 'Una tortuga', 'Un porc', 'Un gat', 'Un dinosaure'],
    ['Qui va ser el mestre d\'en Goku i en Krilin?', 'El Follet Tortuga', 'En Kaito', 'En Cor Petit', 'La Xixi'],
    ['12 ÷ 4 = ?', '3', '4', '6', '8'],
    ['De quin color és la pell d\'en Cor Petit?', 'Verda', 'Blava', 'Rosa', 'Morada']
  ],
  karin: [
    ['Com més en treus, més gran es fa. Què és?', 'Un forat', 'Una mongeta', 'Un núvol', 'Una torre'],
    ['Vola sense ales i plora sense ulls.', 'Un núvol', 'En Goku', 'Un ocell', 'Un drac'],
    ['Té dents i no menja, té barba i no és home.', 'L\'all', 'El Follet Tortuga', 'En Karin', 'Una pinta'],
    ['Si em dius pel meu nom, desapareixo.', 'El silenci', 'Un fantasma', 'L\'ombra', 'El vent'],
    ['Com més s\'asseca, més mulla.', 'La tovallola', 'La pluja', 'El sol', 'Una esponja'],
    ['Puja plena i baixa buida... què és?', 'La cullera', 'La torre', 'L\'ascensor', 'La gerra'],
    ['Tinc agulles i no sé cosir, tinc números i no sé llegir.', 'El rellotge', 'L\'eriçó', 'El scouter', 'Un llibre'],
    ['Sóc blanc com la neu i a la tassa em fonc.', 'El sucre', 'La llet', 'Un núvol', 'El gel']
  ],
  oolong: [
    ['Quant de temps aguanta l\'Oolong transformat?', '5 minuts', '1 hora', 'Un dia', 'Per sempre'],
    ['Per què el van expulsar de l\'escola de transformacions?', 'Per fer trampes', 'Per adormir-se', 'Per menjar molt', 'Per volar'],
    ['Què fa l\'Oolong quan la Bulma diu «pipí-pipí»?', 'Corre al lavabo', 'Es transforma', 'Canta', 'S\'adorm'],
    ['En què NO s\'ha transformat l\'Oolong?', 'En tortuga', 'En toro gegant', 'En robot', 'En ratpenat'],
    ['Què volia l\'Oolong de les noies del poble?', 'Que li cuinessin', 'Les boles de drac', 'Els seus diners', 'Les vaques']
  ]
}
